/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-04-21 17:08:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<meta name=\"author\" content=\"\" />\n");
      out.write("<title>Admin</title>\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/admin/css/styles.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\"\n");
      out.write("	rel=\"stylesheet\" />\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"sb-nav-fixed\">\n");
      out.write("	<nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-dark\">\n");
      out.write("		<!-- Navbar Brand-->\n");
      out.write("		<a class=\"navbar-brand ps-3\" href=\"index.html\">Admin</a>\n");
      out.write("		<!-- Sidebar Toggle-->\n");
      out.write("		<button class=\"btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0\"\n");
      out.write("			id=\"sidebarToggle\" href=\"#!\">\n");
      out.write("			<i class=\"fas fa-bars\"></i>\n");
      out.write("		</button>\n");
      out.write("		<!-- Navbar Search-->\n");
      out.write("		<form\n");
      out.write("			class=\"d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0\">\n");
      out.write("			<div class=\"input-group\">\n");
      out.write("				<input class=\"form-control\" type=\"text\" placeholder=\"Search for...\"\n");
      out.write("					aria-label=\"Search for...\" aria-describedby=\"btnNavbarSearch\" />\n");
      out.write("				<button class=\"btn btn-primary\" id=\"btnNavbarSearch\" type=\"button\">\n");
      out.write("					<i class=\"fas fa-search\"></i>\n");
      out.write("				</button>\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("		<!-- Navbar-->\n");
      out.write("		<ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\n");
      out.write("			<li class=\"nav-item dropdown\"><a\n");
      out.write("				class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\"\n");
      out.write("				role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i\n");
      out.write("					class=\"fas fa-user fa-fw\"></i></a>\n");
      out.write("				<ul class=\"dropdown-menu dropdown-menu-end\"\n");
      out.write("					aria-labelledby=\"navbarDropdown\">\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#!\">Settings</a></li>\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#!\">Activity Log</a></li>\n");
      out.write("					<li><hr class=\"dropdown-divider\" /></li>\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"/ASM_Java4/logout\">Logout</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("		</ul>\n");
      out.write("	</nav>\n");
      out.write("	<div id=\"layoutSidenav\">\n");
      out.write("		<div id=\"layoutSidenav_nav\">\n");
      out.write("			<nav class=\"sb-sidenav accordion sb-sidenav-dark\"\n");
      out.write("				id=\"sidenavAccordion\">\n");
      out.write("				<div class=\"sb-sidenav-menu\">\n");
      out.write("					<div class=\"nav\">\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\">Core</div>\n");
      out.write("						<a class=\"nav-link\" href=\"\">\n");
      out.write("							<div class=\"sb-nav-link-icon\">\n");
      out.write("								<i class=\"fas fa-tachometer-alt\"></i>\n");
      out.write("							</div> Trang chủ\n");
      out.write("						</a>\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\">Quản lý</div>\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\n");
      out.write("							data-bs-target=\"#collapseLayouts1\" aria-expanded=\"false\"\n");
      out.write("							aria-controls=\"collapseLayouts\">\n");
      out.write("							<div class=\"sb-nav-link-icon\">\n");
      out.write("								<i class=\"fas fa-columns\"></i>\n");
      out.write("							</div> Quản lý Bán Hàng\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\n");
      out.write("							</div>\n");
      out.write("						</a>\n");
      out.write("						<div class=\"collapse\" id=\"collapseLayouts1\"\n");
      out.write("							aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav\">\n");
      out.write("								<a class=\"nav-link\" href=\"/ASM_Java4/admin/orders/xacnhan\"> Hóa\n");
      out.write("									đơn xác nhận</a> \n");
      out.write("										<a class=\"nav-link\" href=\"/ASM_Java4/admin/orders/danggiao\"> Hóa\n");
      out.write("									đơn đang giao hàng</a> \n");
      out.write("									<a class=\"nav-link\" href=\"/ASM_Java4/admin/orders/dahuy\">Hóa\n");
      out.write("									đơn đã hủy</a> \n");
      out.write("									<a class=\"nav-link\" href=\"/ASM_Java4/admin/orders/dagiao\"> Hóa\n");
      out.write("									đơn đã giao</a> \n");
      out.write("							</nav>\n");
      out.write("						</div>\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\n");
      out.write("							data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\"\n");
      out.write("							aria-controls=\"collapseLayouts\">\n");
      out.write("							<div class=\"sb-nav-link-icon\">\n");
      out.write("								<i class=\"fas fa-columns\"></i>\n");
      out.write("							</div> Quản lý hàng hóa\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\n");
      out.write("							</div>\n");
      out.write("						</a>\n");
      out.write("						<div class=\"collapse\" id=\"collapseLayouts\"\n");
      out.write("							aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav\">\n");
      out.write("								 <a class=\"nav-link\" href=\"/ASM_Java4/admin/products/index\">Quản\n");
      out.write("									Sản phẩm </a> <a class=\"nav-link\" href=\"/ASM_Java4/admin/categories/index\">Quản\n");
      out.write("									Danh mục</a>\n");
      out.write("							</nav>\n");
      out.write("						</div>\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\n");
      out.write("							data-bs-target=\"#collapsePages\" aria-expanded=\"false\"\n");
      out.write("							aria-controls=\"collapsePages\">\n");
      out.write("							<div class=\"sb-nav-link-icon\">\n");
      out.write("								<i class=\"fas fa-book-open\"></i>\n");
      out.write("							</div> Quản lý tài khoản\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\n");
      out.write("							</div>\n");
      out.write("						</a>\n");
      out.write("						<div class=\"collapse\" id=\"collapsePages\"\n");
      out.write("							aria-labelledby=\"headingTwo\" data-bs-parent=\"#sidenavAccordion\">\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav accordion\"\n");
      out.write("								id=\"sidenavAccordionPages\">\n");
      out.write("								<a class=\"nav-link \" href=\"/ASM_Java4/admin/users/index\" > Quản lý tài khoản </a>\n");
      out.write("							</nav>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\">Addons</div>\n");
      out.write("						<a class=\"nav-link\" href=\"charts.html\">\n");
      out.write("							<div class=\"sb-nav-link-icon\">\n");
      out.write("								<i class=\"fas fa-chart-area\"></i>\n");
      out.write("							</div> Charts\n");
      out.write("						</a> <a class=\"nav-link\" href=\"tables.html\">\n");
      out.write("							<div class=\"sb-nav-link-icon\">\n");
      out.write("								<i class=\"fas fa-table\"></i>\n");
      out.write("							</div> Tables\n");
      out.write("						</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"sb-sidenav-footer\">\n");
      out.write("					<div class=\"small\">Logged in as:</div>\n");
      out.write("					Start Bootstrap\n");
      out.write("				</div>\n");
      out.write("			</nav>\n");
      out.write("		</div>\n");
      out.write("		<div id=\"layoutSidenav_content\">\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\n");
      out.write("			<footer class=\"py-4 bg-light mt-auto\">\n");
      out.write("				<div class=\"container-fluid px-4\">\n");
      out.write("					<div\n");
      out.write("						class=\"d-flex align-items-center justify-content-between small\">\n");
      out.write("						<div class=\"text-muted\">Copyright &copy; Your Website 2021</div>\n");
      out.write("						<div>\n");
      out.write("							<a href=\"#\">Privacy Policy</a> &middot; <a href=\"#\">Terms\n");
      out.write("								&amp; Conditions</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</footer>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script src=\"js/scripts.js\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script src=\"assets/demo/chart-area-demo.js\"></script>\n");
      out.write("	<script src=\"assets/demo/chart-bar-demo.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script src=\"js/datatables-simple-demo.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
