/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-04-25 01:18:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/Java4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ASM_Java4/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1647390950154L));
    _jspx_dependants.put("jar:file:/D:/Java4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ASM_Java4/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"cont span_2_of_3\">\r\n");
      out.write("		<div class=\"grid images_3_of_2\">\r\n");
      out.write("			<img src=\"/ASM_Java4/image/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\">\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"desc1 span_3_of_2\">\r\n");
      out.write("			<h3 class=\"m_3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ten}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("			<p class=\"m_5\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.donGia}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<strong>Màu sắc</strong> : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.mauSac }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			</p>\r\n");
      out.write("			<p>\r\n");
      out.write("				<strong>Size</strong> : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.kichThuoc }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			</p>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"btn_form\">\r\n");
      out.write("				<form action=\"/ASM_Java4/users/cart\" method=\"post\">\r\n");
      out.write("					<p>\r\n");
      out.write("						<input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <strong>Số\r\n");
      out.write("							lượng</strong> :<input type=\"number\" class=\"fw-bold\" name=\"quantity\" id=\"\"\r\n");
      out.write("							style=\"width: 50px; text-align: center;\" min=\"1\"\r\n");
      out.write("							max=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.soLuong }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"1\"> <i class=\"text-muted\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.soLuong }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("							sản phẩm có sẳn</i>\r\n");
      out.write("					</p>\r\n");
      out.write("					<button type=\"submit\" style=\"font-family: 'Exo 2', sans-serif;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("    padding: 10px 34px;\r\n");
      out.write("    background: #4CB1CA;\r\n");
      out.write("    color: #FFF;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    -webkit-transition: all 0.3s ease-in-out;\r\n");
      out.write("    -moz-transition: all 0.3s ease-in-out;\r\n");
      out.write("    -o-transition: all 0.3s ease-in-out;\r\n");
      out.write("    transition: all 0.3s ease-in-out;\">Thêm vào\r\n");
      out.write("						giỏ hàng</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<span class=\"m_link\"><a href=\"#\">login to save in wishlist</a>\r\n");
      out.write("			</span>\r\n");
      out.write("			<p class=\"m_text2\">Lorem ipsum dolor sit amet, consectetuer\r\n");
      out.write("				adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet\r\n");
      out.write("				dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam,\r\n");
      out.write("				quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut\r\n");
      out.write("				aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in\r\n");
      out.write("				hendrerit in vulputate velit esse molestie consequat, vel illum\r\n");
      out.write("				dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto\r\n");
      out.write("				odio dignissim qui blandit</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"clear\"></div>\r\n");
      out.write("		<div class=\"clients\">\r\n");
      out.write("\r\n");
      out.write("			<script type=\"text/javascript\">\r\n");
      out.write("				$(window).load(function() {\r\n");
      out.write("					$(\"#flexiselDemo1\").flexisel();\r\n");
      out.write("					$(\"#flexiselDemo2\").flexisel({\r\n");
      out.write("						enableResponsiveBreakpoints : true,\r\n");
      out.write("						responsiveBreakpoints : {\r\n");
      out.write("							portrait : {\r\n");
      out.write("								changePoint : 480,\r\n");
      out.write("								visibleItems : 1\r\n");
      out.write("							},\r\n");
      out.write("							landscape : {\r\n");
      out.write("								changePoint : 640,\r\n");
      out.write("								visibleItems : 2\r\n");
      out.write("							},\r\n");
      out.write("							tablet : {\r\n");
      out.write("								changePoint : 768,\r\n");
      out.write("								visibleItems : 3\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("\r\n");
      out.write("					$(\"#flexiselDemo3\").flexisel({\r\n");
      out.write("						visibleItems : 5,\r\n");
      out.write("						animationSpeed : 1000,\r\n");
      out.write("						autoPlay : false,\r\n");
      out.write("						autoPlaySpeed : 3000,\r\n");
      out.write("						pauseOnHover : true,\r\n");
      out.write("						enableResponsiveBreakpoints : true,\r\n");
      out.write("						responsiveBreakpoints : {\r\n");
      out.write("							portrait : {\r\n");
      out.write("								changePoint : 480,\r\n");
      out.write("								visibleItems : 1\r\n");
      out.write("							},\r\n");
      out.write("							landscape : {\r\n");
      out.write("								changePoint : 640,\r\n");
      out.write("								visibleItems : 2\r\n");
      out.write("							},\r\n");
      out.write("							tablet : {\r\n");
      out.write("								changePoint : 768,\r\n");
      out.write("								visibleItems : 3\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("\r\n");
      out.write("				});\r\n");
      out.write("			</script>\r\n");
      out.write("			<script type=\"text/javascript\" src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"toogle\">\r\n");
      out.write("			<h3 class=\"m_3\">Product Details</h3>\r\n");
      out.write("			<p class=\"m_text\">Lorem ipsum dolor sit amet, consectetuer\r\n");
      out.write("				adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet\r\n");
      out.write("				dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam,\r\n");
      out.write("				quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut\r\n");
      out.write("				aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in\r\n");
      out.write("				hendrerit in vulputate velit esse molestie consequat, vel illum\r\n");
      out.write("				dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto\r\n");
      out.write("				odio dignissim qui blandit praesent luptatum zzril delenit augue\r\n");
      out.write("				duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta\r\n");
      out.write("				nobis eleifend option congue nihil imperdiet doming id quod mazim\r\n");
      out.write("				placerat facer possim assum.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"toogle\">\r\n");
      out.write("			<h3 class=\"m_3\">More Information</h3>\r\n");
      out.write("			<p class=\"m_text\">Lorem ipsum dolor sit amet, consectetuer\r\n");
      out.write("				adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet\r\n");
      out.write("				dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam,\r\n");
      out.write("				quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut\r\n");
      out.write("				aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in\r\n");
      out.write("				hendrerit in vulputate velit esse molestie consequat, vel illum\r\n");
      out.write("				dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto\r\n");
      out.write("				odio dignissim qui blandit praesent luptatum zzril delenit augue\r\n");
      out.write("				duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta\r\n");
      out.write("				nobis eleifend option congue nihil imperdiet doming id quod mazim\r\n");
      out.write("				placerat facer possim assum.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"rsingle span_1_of_single\">\r\n");
      out.write("		<h5 class=\"m_1\">Categories</h5>\r\n");
      out.write("		<div class=\"metro\">\r\n");
      out.write("			<span class=\"old\"><select class=\"\" tabindex=\"8\"\r\n");
      out.write("				data-settings=\"{&quot;wrapperClass&quot;:&quot;metro&quot;}\"\r\n");
      out.write("				id=\"EasyDropDown507F36\">\r\n");
      out.write("					<option value=\"1\">Mens</option>\r\n");
      out.write("					<option value=\"2\">Sub Category1</option>\r\n");
      out.write("					<option value=\"3\">Sub Category2</option>\r\n");
      out.write("					<option value=\"4\">Sub Category3</option>\r\n");
      out.write("			</select></span><span class=\"selected\">Mens</span><span class=\"carat\"></span>\r\n");
      out.write("			<div>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"active\">Mens</li>\r\n");
      out.write("					<li>Sub Category1</li>\r\n");
      out.write("					<li>Sub Category2</li>\r\n");
      out.write("					<li>Sub Category3</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"metro\">\r\n");
      out.write("			<span class=\"old\"><select class=\"\" tabindex=\"8\"\r\n");
      out.write("				data-settings=\"{&quot;wrapperClass&quot;:&quot;metro&quot;}\"\r\n");
      out.write("				id=\"EasyDropDown2F4D6A\">\r\n");
      out.write("					<option value=\"1\">Womens</option>\r\n");
      out.write("					<option value=\"2\">Sub Category1</option>\r\n");
      out.write("					<option value=\"3\">Sub Category2</option>\r\n");
      out.write("					<option value=\"4\">Sub Category3</option>\r\n");
      out.write("			</select></span><span class=\"selected\">Womens</span><span class=\"carat\"></span>\r\n");
      out.write("			<div>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"active\">Womens</li>\r\n");
      out.write("					<li>Sub Category1</li>\r\n");
      out.write("					<li>Sub Category2</li>\r\n");
      out.write("					<li>Sub Category3</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<ul class=\"kids\">\r\n");
      out.write("			<li><a href=\"#\">Kids</a></li>\r\n");
      out.write("			<li class=\"last\"><a href=\"#\">Glasses Shop</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<section class=\"sky-form\">\r\n");
      out.write("			<h4>Price</h4>\r\n");
      out.write("			<div class=\"row row1 scroll-pane jspScrollable\" tabindex=\"0\"\r\n");
      out.write("				style=\"overflow: hidden; padding: 0px; width: 313px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"jspContainer\" style=\"width: 313px; height: 200px;\">\r\n");
      out.write("					<div class=\"jspPane\" style=\"padding: 20px; width: 266px; top: 0px;\">\r\n");
      out.write("						<div class=\"col col-4\">\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\" checked=\"\"><i></i>Rs 500 - Rs 700</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col col-4\">\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Rs 700 - Rs 1000</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Rs\r\n");
      out.write("								1000 - Rs 1500</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Rs 1500 - Rs 2000</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Rs 2000 - Rs 2500</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Rs\r\n");
      out.write("								2500 - Rs 3000</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Rs 3500 - Rs 4000</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Rs 4000 - Rs 4500</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Rs\r\n");
      out.write("								4500 - Rs 5000</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Rs 5000 - Rs 5500</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Rs 5500 - Rs 6000</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Rs\r\n");
      out.write("								6000 - Rs 6500</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Rs 6500 - Rs 7000</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Rs 7000 - Rs 7500</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Rs\r\n");
      out.write("								7500 - Rs 8000</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Rs 8000 - Rs 8500</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"jspVerticalBar\">\r\n");
      out.write("						<div class=\"jspCap jspCapTop\"></div>\r\n");
      out.write("						<div class=\"jspTrack\" style=\"height: 200px;\">\r\n");
      out.write("							<div class=\"jspDrag\" style=\"height: 76px;\">\r\n");
      out.write("								<div class=\"jspDragTop\"></div>\r\n");
      out.write("								<div class=\"jspDragBottom\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"jspCap jspCapBottom\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section class=\"sky-form\">\r\n");
      out.write("			<h4>Brand Name</h4>\r\n");
      out.write("			<div class=\"row row1 scroll-pane jspScrollable\" tabindex=\"0\"\r\n");
      out.write("				style=\"overflow: hidden; padding: 0px; width: 313px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"jspContainer\" style=\"width: 313px; height: 200px;\">\r\n");
      out.write("					<div class=\"jspPane\" style=\"padding: 20px; width: 266px; top: 0px;\">\r\n");
      out.write("						<div class=\"col col-4\">\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\" checked=\"\"><i></i>John Jacobs</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col col-4\">\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Tag Heuer</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Lee Cooper</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Mikli</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>S Oliver</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Hackett</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Killer</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>IDEE</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Vogue</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Gunnar</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Accu Reader</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>CAT</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Excellent</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Feelgood</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Odysey</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Animal</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"jspVerticalBar\">\r\n");
      out.write("						<div class=\"jspCap jspCapTop\"></div>\r\n");
      out.write("						<div class=\"jspTrack\" style=\"height: 200px;\">\r\n");
      out.write("							<div class=\"jspDrag\" style=\"height: 76px;\">\r\n");
      out.write("								<div class=\"jspDragTop\"></div>\r\n");
      out.write("								<div class=\"jspDragBottom\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"jspCap jspCapBottom\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section class=\"sky-form\">\r\n");
      out.write("			<h4>Frame Shape</h4>\r\n");
      out.write("			<div class=\"row row1 scroll-pane jspScrollable\" tabindex=\"0\"\r\n");
      out.write("				style=\"overflow: hidden; padding: 0px; width: 313px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"jspContainer\" style=\"width: 313px; height: 200px;\">\r\n");
      out.write("					<div class=\"jspPane\" style=\"padding: 20px; width: 266px; top: 0px;\">\r\n");
      out.write("						<div class=\"col col-4\">\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\" checked=\"\"><i></i>Pilot</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col col-4\">\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Rectangle</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Square</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Round</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Others</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Cat Eyes</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Wrap\r\n");
      out.write("								Around</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"jspVerticalBar\">\r\n");
      out.write("						<div class=\"jspCap jspCapTop\"></div>\r\n");
      out.write("						<div class=\"jspTrack\" style=\"height: 200px;\">\r\n");
      out.write("							<div class=\"jspDrag\" style=\"height: 161px;\">\r\n");
      out.write("								<div class=\"jspDragTop\"></div>\r\n");
      out.write("								<div class=\"jspDragBottom\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"jspCap jspCapBottom\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section class=\"sky-form\">\r\n");
      out.write("			<h4>Frame Size</h4>\r\n");
      out.write("			<div class=\"row row1 scroll-pane\"\r\n");
      out.write("				style=\"overflow: hidden; padding: 0px; width: 313px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"jspContainer\" style=\"width: 313px; height: 200px;\">\r\n");
      out.write("					<div class=\"jspPane\"\r\n");
      out.write("						style=\"padding: 20px; top: 0px; left: 0px; width: 273px;\">\r\n");
      out.write("						<div class=\"col col-4\">\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\" checked=\"\"><i></i>Small</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col col-4\">\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Medium</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Large</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Medium</label>\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Large</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section class=\"sky-form\">\r\n");
      out.write("			<h4>Frame Type</h4>\r\n");
      out.write("			<div class=\"row row1 scroll-pane\"\r\n");
      out.write("				style=\"overflow: hidden; padding: 0px; width: 313px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"jspContainer\" style=\"width: 313px; height: 200px;\">\r\n");
      out.write("					<div class=\"jspPane\"\r\n");
      out.write("						style=\"padding: 20px; top: 0px; left: 0px; width: 273px;\">\r\n");
      out.write("						<div class=\"col col-4\">\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\" checked=\"\"><i></i>Full Rim</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col col-4\">\r\n");
      out.write("							<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Rim Less</label> <label class=\"checkbox\"><input\r\n");
      out.write("								type=\"checkbox\" name=\"checkbox\"><i></i>Half Rim</label> <label\r\n");
      out.write("								class=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Rim\r\n");
      out.write("								Less</label> <label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("								name=\"checkbox\"><i></i>Half Rim</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section class=\"sky-form\">\r\n");
      out.write("			<h4>Colors</h4>\r\n");
      out.write("			<ul class=\"color-list\">\r\n");
      out.write("				<li><a href=\"#\"> <span class=\"color1\"> </span>\r\n");
      out.write("						<p class=\"red\">Red</p>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"#\"> <span class=\"color2\"> </span>\r\n");
      out.write("						<p class=\"red\">Green</p>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"#\"> <span class=\"color3\"> </span>\r\n");
      out.write("						<p class=\"red\">Blue</p>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"#\"> <span class=\"color4\"> </span>\r\n");
      out.write("						<p class=\"red\">Yellow</p>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"#\"> <span class=\"color5\"> </span>\r\n");
      out.write("						<p class=\"red\">Violet</p>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"#\"> <span class=\"color6\"> </span>\r\n");
      out.write("						<p class=\"red\">Orange</p>\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li><a href=\"#\"> <span class=\"color7\"> </span>\r\n");
      out.write("						<p class=\"red\">Gray</p>\r\n");
      out.write("				</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</section>\r\n");
      out.write("		<script src=\"js/jquery.easydropdown.js\"></script>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
