/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-04-21 17:07:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1647390950154L));
    _jspx_dependants.put("jar:file:/D:/Java4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ASM_Java4/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        \r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Leoshop| Login</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Exo+2' rel='stylesheet' type='text/css'>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/js/jquery1.min.js\"></script>\r\n");
      out.write("<!-- start menu -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/css/megamenu.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/js/megamenu.js\"></script>\r\n");
      out.write("<script>$(document).ready(function(){$(\".megamenu\").megamenu();});</script>\r\n");
      out.write("<!-- dropdown -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/js/jquery.easydropdown.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header-top\">\r\n");
      out.write("			<div class=\"wrap\"> \r\n");
      out.write("			  <div class=\"header-top-left\">\r\n");
      out.write("			  	   <div class=\"box\">\r\n");
      out.write("   				      <select tabindex=\"4\" class=\"dropdown\">\r\n");
      out.write("							<option value=\"\" class=\"label\" value=\"\">Language :</option>\r\n");
      out.write("							<option value=\"1\">English</option>\r\n");
      out.write("							<option value=\"2\">French</option>\r\n");
      out.write("							<option value=\"3\">German</option>\r\n");
      out.write("					  </select>\r\n");
      out.write("   				    </div>\r\n");
      out.write("   				    <div class=\"box1\">\r\n");
      out.write("   				        <select tabindex=\"4\" class=\"dropdown\">\r\n");
      out.write("							<option value=\"\" class=\"label\" value=\"\">Currency :</option>\r\n");
      out.write("							<option value=\"1\">$ Dollar</option>\r\n");
      out.write("							<option value=\"2\">â¬ Euro</option>\r\n");
      out.write("						</select>\r\n");
      out.write("   				    </div>\r\n");
      out.write("   				    <div class=\"clear\"></div>\r\n");
      out.write("   			 </div>\r\n");
      out.write("			 <div class=\"cssmenu\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"login.html\">Log In</a></li> |\r\n");
      out.write("					<li><a href=\"register.html\">Sign Up</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clear\"></div>\r\n");
      out.write(" 		</div>\r\n");
      out.write("	 </div>\r\n");
      out.write("	<div class=\"header-bottom\">\r\n");
      out.write("	    <div class=\"wrap\">\r\n");
      out.write("			<div class=\"header-bottom-left\">\r\n");
      out.write("				<div class=\"logo\">\r\n");
      out.write("					<a href=\"/ASM_Java4/users/index\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/images/logo.png\" alt=\"\"/></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"menu\">\r\n");
      out.write("	            <ul class=\"megamenu skyblue\">\r\n");
      out.write("			<li class=\"active grid\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("			<li><a class=\"color4\" href=\"#\">women</a>\r\n");
      out.write("				<div class=\"megapanel\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col1\">\r\n");
      out.write("							<div class=\"h_nav\">\r\n");
      out.write("								<h4>Contact Lenses</h4>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"womens.html\">Daily-wear soft lenses</a></li>\r\n");
      out.write("									<li><a href=\"womens.html\">Extended-wear</a></li>\r\n");
      out.write("									<li><a href=\"womens.html\">Lorem ipsum </a></li>\r\n");
      out.write("									<li><a href=\"womens.html\">Planned replacement</a></li>\r\n");
      out.write("								</ul>	\r\n");
      out.write("							</div>							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col1\">\r\n");
      out.write("							<div class=\"h_nav\">\r\n");
      out.write("								<h4>Sun Glasses</h4>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"womens.html\">Heart-Shaped</a></li>\r\n");
      out.write("									<li><a href=\"womens.html\">Square-Shaped</a></li>\r\n");
      out.write("									<li><a href=\"womens.html\">Round-Shaped</a></li>\r\n");
      out.write("									<li><a href=\"womens.html\">Oval-Shaped</a></li>\r\n");
      out.write("								</ul>	\r\n");
      out.write("							</div>							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col1\">\r\n");
      out.write("							<div class=\"h_nav\">\r\n");
      out.write("								<h4>Eye Glasses</h4>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"womens.html\">Anti Reflective</a></li>\r\n");
      out.write("									<li><a href=\"womens.html\">Aspheric</a></li>\r\n");
      out.write("									<li><a href=\"womens.html\">Bifocal</a></li>\r\n");
      out.write("									<li><a href=\"womens.html\">Hi-index</a></li>\r\n");
      out.write("									<li><a href=\"womens.html\">Progressive</a></li>\r\n");
      out.write("								</ul>	\r\n");
      out.write("							</div>												\r\n");
      out.write("						</div>\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>				\r\n");
      out.write("				<li><a class=\"color5\" href=\"#\">Men</a>\r\n");
      out.write("				<div class=\"megapanel\">\r\n");
      out.write("					<div class=\"col1\">\r\n");
      out.write("							<div class=\"h_nav\">\r\n");
      out.write("								<h4>Contact Lenses</h4>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"mens.html\">Daily-wear soft lenses</a></li>\r\n");
      out.write("									<li><a href=\"mens.html\">Extended-wear</a></li>\r\n");
      out.write("									<li><a href=\"mens.html\">Lorem ipsum </a></li>\r\n");
      out.write("									<li><a href=\"mens.html\">Planned replacement</a></li>\r\n");
      out.write("								</ul>	\r\n");
      out.write("							</div>							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col1\">\r\n");
      out.write("							<div class=\"h_nav\">\r\n");
      out.write("								<h4>Sun Glasses</h4>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"mens.html\">Heart-Shaped</a></li>\r\n");
      out.write("									<li><a href=\"mens.html\">Square-Shaped</a></li>\r\n");
      out.write("									<li><a href=\"mens.html\">Round-Shaped</a></li>\r\n");
      out.write("									<li><a href=\"mens.html\">Oval-Shaped</a></li>\r\n");
      out.write("								</ul>	\r\n");
      out.write("							</div>							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col1\">\r\n");
      out.write("							<div class=\"h_nav\">\r\n");
      out.write("								<h4>Eye Glasses</h4>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"mens.html\">Anti Reflective</a></li>\r\n");
      out.write("									<li><a href=\"mens.html\">Aspheric</a></li>\r\n");
      out.write("									<li><a href=\"mens.html\">Bifocal</a></li>\r\n");
      out.write("									<li><a href=\"mens.html\">Hi-index</a></li>\r\n");
      out.write("									<li><a href=\"mens.html\">Progressive</a></li>\r\n");
      out.write("								</ul>	\r\n");
      out.write("							</div>												\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li><a class=\"color6\" href=\"other.html\">Other</a></li>\r\n");
      out.write("				<li><a class=\"color7\" href=\"other.html\">Purchase</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	   <div class=\"header-bottom-right\">\r\n");
      out.write("         <div class=\"search\">	  \r\n");
      out.write("				<input type=\"text\" name=\"s\" class=\"textbox\" value=\"Search\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Search';}\">\r\n");
      out.write("				<input type=\"submit\" value=\"Subscribe\" id=\"submit\" name=\"submit\">\r\n");
      out.write("				<div id=\"response\"> </div>\r\n");
      out.write("		 </div>\r\n");
      out.write("	  <div class=\"tag-list\">\r\n");
      out.write("	    <ul class=\"icon1 sub-icon1 profile_img\">\r\n");
      out.write("			<li><a class=\"active-icon c1\" href=\"#\"> </a>\r\n");
      out.write("				<ul class=\"sub-icon1 list\">\r\n");
      out.write("					<li><h3>sed diam nonummy</h3><a href=\"\"></a></li>\r\n");
      out.write("					<li><p>Lorem ipsum dolor sit amet, consectetuer  <a href=\"\">adipiscing elit, sed diam</a></p></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<ul class=\"icon1 sub-icon1 profile_img\">\r\n");
      out.write("			<li><a class=\"active-icon c2\" href=\"#\"> </a>\r\n");
      out.write("				<ul class=\"sub-icon1 list\">\r\n");
      out.write("					<li><h3>No Products</h3><a href=\"\"></a></li>\r\n");
      out.write("					<li><p>Lorem ipsum dolor sit amet, consectetuer  <a href=\"\">adipiscing elit, sed diam</a></p></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	    <ul class=\"last\"><li><a href=\"#\">Cart(0)</a></li></ul>\r\n");
      out.write("	  </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"clear\"></div>\r\n");
      out.write("     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("        <div class=\"login\">\r\n");
      out.write("          	<div class=\"wrap\">\r\n");
      out.write("				<div class=\"col_1_of_login span_1_of_login\">\r\n");
      out.write("					<h4 class=\"title\">New Customers</h4>\r\n");
      out.write("					<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan</p>\r\n");
      out.write("					<div class=\"button1\">\r\n");
      out.write("					   <a href=\"register.html\"><input type=\"submit\" name=\"Submit\" value=\"Create an Account\"></a>\r\n");
      out.write("					 </div>\r\n");
      out.write("					 <div class=\"clear\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col_1_of_login span_1_of_login\">\r\n");
      out.write("				<div class=\"login-title\">\r\n");
      out.write("	           		<h4 class=\"title\">Registered Customers</h4>\r\n");
      out.write("					<div id=\"loginbox\" class=\"loginbox\">\r\n");
      out.write("						<form action=\"/ASM_Java4/checklogin\" method=\"post\" name=\"login\" id=\"login-form\">\r\n");
      out.write("						  <fieldset class=\"input\">\r\n");
      out.write("						    <p id=\"login-form-username\">\r\n");
      out.write("						      <label for=\"modlgn_username\">Email</label>\r\n");
      out.write("							\r\n");
      out.write("						      <input id=\"modlgn_username\" type=\"text\" name=\"email\" class=\"inputbox\" size=\"18\" autocomplete=\"off\">\r\n");
      out.write("						        <span style=\"text-color:red\"><i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</i></span>\r\n");
      out.write("						    </p>\r\n");
      out.write("						    <p id=\"login-form-password\">\r\n");
      out.write("						      <label for=\"modlgn_passwd\">Password</label>\r\n");
      out.write("						      <input id=\"modlgn_passwd\" type=\"password\" name=\"password\" class=\"inputbox\" size=\"18\" autocomplete=\"off\">\r\n");
      out.write("						      \r\n");
      out.write("						    </p>\r\n");
      out.write("						    <div class=\"remember\">\r\n");
      out.write("							    <p id=\"login-form-remember\">\r\n");
      out.write("							      <label for=\"modlgn_remember\"><a href=\"#\">Forget Your Password ? </a></label>\r\n");
      out.write("							   </p>\r\n");
      out.write("							    <input type=\"submit\" name=\"Submit\" class=\"button\" value=\"Login\"><div class=\"clear\"></div>\r\n");
      out.write("							 </div>\r\n");
      out.write("						  </fieldset>\r\n");
      out.write("						 </form>\r\n");
      out.write("					</div>\r\n");
      out.write("			    </div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clear\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("     <div class=\"footer\">\r\n");
      out.write("		<div class=\"footer-top\">\r\n");
      out.write("			<div class=\"wrap\">\r\n");
      out.write("			  <div class=\"section group example\">\r\n");
      out.write("				<div class=\"col_1_of_2 span_1_of_2\">\r\n");
      out.write("					<ul class=\"f-list\">\r\n");
      out.write("					  <li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/images/2.png\"><span class=\"f-text\">Free Shipping on orders over $ 100</span><div class=\"clear\"></div></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col_1_of_2 span_1_of_2\">\r\n");
      out.write("					<ul class=\"f-list\">\r\n");
      out.write("					  <li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/images/3.png\"><span class=\"f-text\">Call us! toll free-222-555-6666 </span><div class=\"clear\"></div></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clear\"></div>\r\n");
      out.write("		      </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer-middle\">\r\n");
      out.write("			<div class=\"wrap\">\r\n");
      out.write("			 <div class=\"section group example\">\r\n");
      out.write("			  <div class=\"col_1_of_f_1 span_1_of_f_1\">\r\n");
      out.write("				 <div class=\"section group example\">\r\n");
      out.write("				   <div class=\"col_1_of_f_2 span_1_of_f_2\">\r\n");
      out.write("				      <h3>Facebook</h3>\r\n");
      out.write("						<script>(function(d, s, id) {\r\n");
      out.write("						  var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("						  if (d.getElementById(id)) return;\r\n");
      out.write("						  js = d.createElement(s); js.id = id;\r\n");
      out.write("						  js.src = \"//connect.facebook.net/en_US/all.js#xfbml=1\";\r\n");
      out.write("						  fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("						}(document, 'script', 'facebook-jssdk'));</script>\r\n");
      out.write("						<div class=\"like_box\">	\r\n");
      out.write("							<div class=\"fb-like-box\" data-href=\"http://www.facebook.com/w3layouts\" data-colorscheme=\"light\" data-show-faces=\"true\" data-header=\"true\" data-stream=\"false\" data-show-border=\"true\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write(" 				  </div>\r\n");
      out.write("				  <div class=\"col_1_of_f_2 span_1_of_f_2\">\r\n");
      out.write("						<h3>From Twitter</h3>\r\n");
      out.write("				       <div class=\"recent-tweet\">\r\n");
      out.write("							<div class=\"recent-tweet-icon\">\r\n");
      out.write("								<span> </span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"recent-tweet-info\">\r\n");
      out.write("								<p>Ds which don't look even slightly believable. If you are <a href=\"#\">going to use nibh euismod</a> tincidunt ut laoreet adipisicing</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clear\"> </div>\r\n");
      out.write("					   </div>\r\n");
      out.write("					   <div class=\"recent-tweet\">\r\n");
      out.write("							<div class=\"recent-tweet-icon\">\r\n");
      out.write("								<span> </span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"recent-tweet-info\">\r\n");
      out.write("								<p>Ds which don't look even slightly believable. If you are <a href=\"#\">going to use nibh euismod</a> tincidunt ut laoreet adipisicing</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clear\"> </div>\r\n");
      out.write("					  </div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clear\"></div>\r\n");
      out.write("		      </div>\r\n");
      out.write(" 			 </div>\r\n");
      out.write("			 <div class=\"col_1_of_f_1 span_1_of_f_1\">\r\n");
      out.write("			   <div class=\"section group example\">\r\n");
      out.write("				 <div class=\"col_1_of_f_2 span_1_of_f_2\">\r\n");
      out.write("				    <h3>Information</h3>\r\n");
      out.write("						<ul class=\"f-list1\">\r\n");
      out.write("						    <li><a href=\"#\">Duis autem vel eum iriure </a></li>\r\n");
      out.write("				            <li><a href=\"#\">anteposuerit litterarum formas </a></li>\r\n");
      out.write("				            <li><a href=\"#\">Tduis dolore te feugait nulla</a></li>\r\n");
      out.write("				             <li><a href=\"#\">Duis autem vel eum iriure </a></li>\r\n");
      out.write("				            <li><a href=\"#\">anteposuerit litterarum formas </a></li>\r\n");
      out.write("				            <li><a href=\"#\">Tduis dolore te feugait nulla</a></li>\r\n");
      out.write("			         	</ul>\r\n");
      out.write(" 				 </div>\r\n");
      out.write("				 <div class=\"col_1_of_f_2 span_1_of_f_2\">\r\n");
      out.write("				   <h3>Contact us</h3>\r\n");
      out.write("						<div class=\"company_address\">\r\n");
      out.write("					                <p>500 Lorem Ipsum Dolor Sit,</p>\r\n");
      out.write("							   		<p>22-56-2-9 Sit Amet, Lorem,</p>\r\n");
      out.write("							   		<p>USA</p>\r\n");
      out.write("					   		<p>Phone:(00) 222 666 444</p>\r\n");
      out.write("					   		<p>Fax: (000) 000 00 00 0</p>\r\n");
      out.write("					 	 	<p>Email: <span>mail[at]leoshop.com</span></p>\r\n");
      out.write("					   		\r\n");
      out.write("					   </div>\r\n");
      out.write("					   <div class=\"social-media\">\r\n");
      out.write("						     <ul>\r\n");
      out.write("						        <li> <span class=\"simptip-position-bottom simptip-movable\" data-tooltip=\"Google\"><a href=\"#\" target=\"_blank\"> </a></span></li>\r\n");
      out.write("						        <li><span class=\"simptip-position-bottom simptip-movable\" data-tooltip=\"Linked in\"><a href=\"#\" target=\"_blank\"> </a> </span></li>\r\n");
      out.write("						        <li><span class=\"simptip-position-bottom simptip-movable\" data-tooltip=\"Rss\"><a href=\"#\" target=\"_blank\"> </a></span></li>\r\n");
      out.write("						        <li><span class=\"simptip-position-bottom simptip-movable\" data-tooltip=\"Facebook\"><a href=\"#\" target=\"_blank\"> </a></span></li>\r\n");
      out.write("						    </ul>\r\n");
      out.write("					   </div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clear\"></div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		   </div>\r\n");
      out.write("		  <div class=\"clear\"></div>\r\n");
      out.write("		    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer-bottom\">\r\n");
      out.write("			<div class=\"wrap\">\r\n");
      out.write("	            <div class=\"copy\">\r\n");
      out.write("			           <p>Â© 2014 Template by <a href=\"http://w3layouts.com\" target=\"_blank\">w3layouts</a></p>\r\n");
      out.write("		        </div>\r\n");
      out.write("			  <div class=\"f-list2\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"active\"><a href=\"about.html\">About Us</a></li> |\r\n");
      out.write("					<li><a href=\"delivery.html\">Delivery & Returns</a></li> |\r\n");
      out.write("					<li><a href=\"delivery.html\">Terms & Conditions</a></li> |\r\n");
      out.write("					<li><a href=\"contact.html\">Contact Us</a></li> \r\n");
      out.write("				</ul>\r\n");
      out.write("			  </div>\r\n");
      out.write("				<div class=\"clear\"></div>\r\n");
      out.write("		      </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
